STACK SEGMENT STACK
    DB 256 DUP(?)
STACK ENDS
DATA SEGMENT
    BUF DB 50 DUP(?)
    MIN DB FFH
DATA ENDS
CODE SEGMENT
ASSUME CS:CODE, DS:DATA, ES:DATA, SS:STACK
START:
    MOV AX, DATA
    MOV DS, AX
    MOV ES, AX
    LEA SI, BUF
    MOV AL, MIN
    MOV CX, 50
COMPARE:
    MOV AH, [SI]
    CMP AH, AL
    JAE NEXT
    MOV AL, AH
NEXT:
    LOOP COMPARE
FINISH:
    MOV AH, 4CH
    INT 21H
CODE ENDS
END START