STACK SEGMENT STACK
    DB 256 DUP(?)
STACK ENDS
DATA SEGMENT
    BUF DB 'AABA'
    CNT DW $-BUF
    DAT DB 'A'
    VAR1 DB ?, '$'
DATA ENDS
CODE SEGMENT
ASSUME CS:CODE, DS:DATA, ES:DATA, SS:STACK
START:
    MOV AX, DATA
    MOV DS, AX
    MOV ES, AX
    LEA DI, BUF
    MOV CX, CNT
    cld
    MOV AL, DAT
    REPNZ SCASB

    MOV BYTE PTR VAR1, CL
    MOV DX, OFFSET VAR1
    MOV AH, 9
    INT 21H

FINISH:
    MOV AH, 4CH
    INT 21H
CODE ENDS
END START