STACK SEGMENT STACK
    DB 256 DUP(?)
STACK ENDS
DATA SEGMENT
    BUF DB 99 DUP(?)
        DB '$'
    DETSS DB 0
DATA ENDS
CODE SEGMENT
ASSUME CS:CODE, DS:DATA, ES:DATA, SS:STACK
START:
    MOV AX, DATA
    MOV DS, AX
    MOV ES, AX
    MOV AL, '$'
    MOV CX, 100
    LEA SI, BUF
    CLD
    REPNZ SCASB
    JCXZ FINISH
    MOV DETSS, AL
FINISH:
    MOV AH, 4CH
    INT 21H
CODE ENDS
END START