STACK SEGMENT STACK
    DB 256 DUP(?)
STACK ENDS
DATA SEGMENT
    S1 DB 02H, 05H
    S2 DB 00H
DATA ENDS
CODE SEGMENT
ASSUME CS:CODE, DS:DATA, ES:DATA, SS:STACK
START:
    MOV AX, DATA
    MOV DS, AX
    MOV ES, AX
    LEA S1, SI
    MOV AH, [SI]
    MOV AL, [SI+1]
    AND AL, 0FH
    MOV CX, 4
    SHL AH, CX
    ADD AL, AH
    MOV S2, AL
FINISH:
    MOV AH, 4CH
    INT 21H
CODE ENDS
END START