STACK SEGMENT STACK
    DB 256 DUP(?)
STACK ENDS
DATA SEGMENT
    TES DW ?
DATA ENDS
CODE SEGMENT
ASSUME CS:CODE, DS:DATA, ES:DATA, SS:STACK
START:
    MOV BX, OFFSET TES
    MOV [BX], 0101H
FINISH:
    MOV AH, 4CH
    INT 21H
CODE ENDS
END START