STACK SEGMENT STACK
    DB 256 DUP(?)
STACK ENDS
DATA SEGMENT
    ORG 0120H
    DAT1 DW 0,1,2,3,4,5,6,7,8,9
    COUNT EQU $-DAT1
DATA ENDS
CODE SEGMENT
ASSUME CS:CODE, DS:DATA, ES:DATA, SS:STACK
START:
    MOV AX, DATA
    MOV DS, AX
    MOV ES, AX
    MOV DI, OFFSET DAT1
    MOV AX, 3
    cld
    MOV CX, COUNT/2
    REPNZ SCASW
    
    MOV BX, 112

FINISH:
    MOV AH, 4CH
    INT 21H
CODE ENDS
END START