STACK SEGMENT STACK
    DB 256 DUP(?)
STACK ENDS
DATA SEGMENT
    VAR1 DB ?, '$'
DATA ENDS
CODE SEGMENT
ASSUME CS:CODE, DS:DATA, ES:DATA, SS:STACK
START:
    MOV AX, DATA
    MOV DS, AX
    MOV ES, AX
    MOV AX, -50
    ADD AX, -5
    PUSHF
    POP DX
    AND DL, 00010000B
    JZ AF0
    JNZ AF1
AF0:
    MOV DL, 0
    JMP SHOW
AF1:
    MOV DL, 1
    JMP SHOW
SHOW:    
    ADD DL, '0'
    MOV BYTE PTR VAR1, DL
    MOV DX, OFFSET VAR1
    MOV AH, 9
    INT 21H

FINISH:
    MOV AH, 4CH
    INT 21H
CODE ENDS
END START