STACK SEGMENT STACK
    DB 256 DUP(?)
STACK ENDS
DATA SEGMENT
    A DW 1234H
    B DW 5678H
DATA ENDS
CODE SEGMENT
ASSUME CS:CODE, DS:DATA, ES:DATA, SS:STACK
START:
    MOV AX, DATA
    MOV DS, AX
    MOV ES, AX
    PUSH A
    PUSH B
    POP A
    POP B
    MOV AX, A
    MOV BX, B
FINISH:
    MOV AH, 4CH
    INT 21H
CODE ENDS
END START