STACK SEGMENT STACK
    DB 256 DUP(?)
STACK ENDS
DATA SEGMENT
DATA ENDS
CODE SEGMENT
ASSUME CS:CODE, DS:DATA, ES:DATA, SS:STACK
START:
    MOV AX, DATA
    MOV DS, AX
    MOV ES, AX
    MOV AX, 6540H
    MOV DX, 3210H
    MOV CL, 04
    SHL DX, CL
    MOV BL, AH
    SHL AX, CL
    SHR BL, CL
    OR DL,BL
FINISH:
    MOV AH, 4CH
    INT 21H
CODE ENDS
END START