STACK SEGMENT STACK
    DB 256 DUP(?)
STACK ENDS
DATA SEGMENT
DATA ENDS
CODE SEGMENT
ASSUME CS:CODE, DS:DATA, ES:DATA, SS:STACK
START:
    MOV AX, DATA
    MOV DS, AX
    MOV ES, AX
    MOV AL, 60H
    MOV BL, 20H
    STC
    ADC AL, BL
    JC CF1
    MOV CX, 1
CF1:
    MOV CX, 2
FINISH:
    MOV AH, 4CH
    INT 21H
CODE ENDS
END START